# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish To Nuget Prerelease

on: workflow_dispatch

env:
  Major: 1
  Minor: 0
  Patch: 2

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    #- name: Upload artifacts
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: GS-LengthConverter-Net6-dll
    #    path: |
    #      ./GS.LengthConverter.Net6/bin/Debug/net6.0/GS.LengthConverter.Net6.dll
    #      retention-days: 1


  #deploy:
    #needs: build
    #runs-on: ubuntu-latest
    #steps:

    #- name: Checkout
    #  uses: actions/checkout@v4
    #  with:
    #    sparse-checkout: |
    #      nuspec/GS.LengthConverter.nuspec
    #    sparse-checkout-cone-mode: false
    #    fetch-depth: 0

    #- name: Download artifacts
    #  uses: actions/download-artifact@v3
    #  with:
    #    name: GS-LengthConverter-Net6-dll

    - name: Install NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: latest

    - name: NuGet Pack
      run: nuget pack ./nuspec/GS.LengthConverter.nuspec -Version $Major.$Minor.$Patch-build-${{github.run_number}}

    - name: NuGet Push
      run: nuget push ./GS.LengthConverter.$Major.$Minor.$Patch-build-${{github.run_number}}.nupkg -src https://api.nuget.org/v3/index.json